# Generated by Django 5.2.8 on 2025-11-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodrecord',
            name='is_predicted',
            field=models.BooleanField(default=True),
        ),
    ]
