# Generated by Django 5.2.8 on 2025-11-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodrecord',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='periodrecord',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
