# Generated by Django 5.2.8 on 2025-11-26 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_periodrecord_is_confirmed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodrecord',
            options={'ordering': ['-start_date'], 'verbose_name': '经期记录', 'verbose_name_plural': '经期记录'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户资料', 'verbose_name_plural': '用户资料'},
        ),
        migrations.RemoveField(
            model_name='periodrecord',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='periodrecord',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='periodrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='periodrecord',
            name='end_date',
            field=models.DateField(verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='periodrecord',
            name='is_predicted',
            field=models.BooleanField(default=False, verbose_name='是否为预测记录'),
        ),
        migrations.AlterField(
            model_name='periodrecord',
            name='start_date',
            field=models.DateField(verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='periodrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cycle_length',
            field=models.IntegerField(default=28, verbose_name='月经周期天数'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PeriodPrediction',
        ),
    ]
